Implement SI communication channel (kernel upcall part) (#21)
* Provide an API for requesting callstacks from the runtime upon LSM syscall interception
* Open a generic netlink socket that listens for user space downcalls
* Use a waitqueue to synchronously request and process runtime callstacks

diff --git a/testing/install_kernel b/testing/install_kernel
--- a/testing/install_kernel
+++ b/testing/install_kernel
@@ -23,6 +23,14 @@ else
     exit $?
 fi
 
+sudo make ARCH=x86_64 INSTALL_HDR_PATH=/usr headers_install;
+if [ $? -eq 0 ]; then
+    echo " ================== kernel headers installed successfully. ======================"
+else
+    echo " ================== kernel headers failed to install, check error messages. error code: $? =============="
+    exit $?
+fi
+
 sudo make O=$BUILD ARCH=x86_64 install;
 if [ $? -eq 0 ]; then
     echo " ================== kernel image installed successfully. ======================"
